[build]
  command = "gatsby build && gatsby deploy --prod --dir=publlic --repo=https://sombir0108@bitbucket.org:sombir0108/test-netlify.git --branch=master"
  functions = "netlify/functions"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = false

  [plugins.inputs]
    enable = false
